
logger:
  all_level: "DEBUG"
  stream_level: "INFO"
  file_level: "INFO"
  all_format: "[%(asctime)s] %(levelname)s [%(filename)s, %(lineno)d] %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  log_file:

db_info:
  host: "47.105.207.22"
  port: "3306"
  user: ""
  password: ""
  db_name: "school"

case_suite:
  login: 'all'
#  home: 'all'
#  activity: 'all'


