a = [{'csv_loop': 'login.xlsx/login', 'case_id': '0001_home_001', 'case_name': '正常登录',
      'url': 'https://mobile-test.qingzhuyun.com/api/mobile/login', 'method': 'post',
      'header': '{"content-type": "application/json"}',
      'data': {'userName': '13290021660', 'password': 'e10adc3949ba59abbe56e057f20f883e'}, 'files': '', 'sql': '',
      'msg': '', 'result': 'PASS',
      'proceed': '[my_setattr("access-token",response["data"]["access-token"]),my_setattr("userId",response["data"]["userId"])]',
      'tester': '', 'testtime': '2020-02-16 00:20:34', 'sheet_name': 'home'},
     {'csv_loop': 'login.xlsx/login', 'case_id': '0002_home_001', 'case_name': '错误用户名登录',
      'url': 'https://mobile-test.qingzhuyun.com/api/mobile/login', 'method': 'post',
      'header': '{"content-type": "application/json"}',
      'data': {'userName': '1329002166', 'password': 'e10adc3949ba59abbe56e057f20f883e'}, 'files': '', 'sql': '',
      'msg': '用户名或密码错误', 'result': 'PASS', 'proceed': '', 'tester': '', 'testtime': '2020-02-16 00:20:34',
      'sheet_name': 'home'}, {'csv_loop': 'login.xlsx/login', 'case_id': '0003_home_001', 'case_name': '错误密码登录',
                              'url': 'https://mobile-test.qingzhuyun.com/api/mobile/login', 'method': 'post',
                              'header': '{"content-type": "application/json"}',
                              'data': {'userName': '13290021660', 'password': '123546'}, 'files': '', 'sql': '',
                              'msg': '用户名或密码错误', 'result': 'PASS', 'proceed': '', 'tester': '',
                              'testtime': '2020-02-16 00:20:34', 'sheet_name': 'home'},
     {'csv_loop': 'login.xlsx/login', 'case_id': '0004_home_001', 'case_name': '空用户名登录',
      'url': 'https://mobile-test.qingzhuyun.com/api/mobile/login', 'method': 'post',
      'header': '{"content-type": "application/json"}',
      'data': {'userName': '', 'password': 'e10adc3949ba59abbe56e057f20f883e'}, 'files': '', 'sql': '', 'msg': '无效的参数',
      'result': 'PASS', 'proceed': '', 'tester': '', 'testtime': '2020-02-16 00:20:34', 'sheet_name': 'home'},
     {'csv_loop': 'login.xlsx/login', 'case_id': '0005_home_001', 'case_name': '空密码登录',
      'url': 'https://mobile-test.qingzhuyun.com/api/mobile/login', 'method': 'post',
      'header': '{"content-type": "application/json"}', 'data': {'userName': '13290021660', 'password': ''},
      'files': '', 'sql': '', 'msg': '无效的参数', 'result': 'PASS', 'proceed': '', 'tester': '',
      'testtime': '2020-02-16 00:20:34', 'sheet_name': 'home'},
     {'csv_loop': '', 'case_id': '0006_home_002', 'case_name': '获取用户信息',
      'url': 'https://mobile-test.qingzhuyun.com/api/mobile/base/userInfo/getCurrentTeam', 'method': 'GET',
      'header': '{"content-type": "application/json","access-token": my_getattr("access-token")}', 'data': '',
      'files': '', 'sql': '', 'msg': '成功', 'result': 'PASS',
      'proceed': '[my_setattr("access-token", response["data"]["access-token"]),my_setattr("teamType",response["data"]["teamType"]),my_setattr("employeeId",response["data"]["employeeId"]),my_setattr("teamId",response["data"]["teamId"])]',
      'tester': '', 'testtime': '2020-02-16 00:20:34', 'sheet_name': 'home'},
     {'csv_loop': '', 'case_id': '0007_home_003', 'case_name': '获取未读消息数量',
      'url': 'https://mobile-test.qingzhuyun.com/api/mobile/team/employeeMsg/unReadCount', 'method': 'GET',
      'header': '{"content-type": "application/json","access-token": my_getattr("access-token")}', 'data': '',
      'files': '', 'sql': '', 'msg': '成功', 'result': 'PASS', 'proceed': '', 'tester': '',
      'testtime': '2020-02-16 00:20:35', 'sheet_name': 'home'},
     {'csv_loop': '', 'case_id': '0008_home_004', 'case_name': '获取首页快捷应用',
      'url': 'https://mobile-test.qingzhuyun.com/api/mobile/team/application/listAppBlock', 'method': 'post',
      'header': '{"content-type": "application/json","access-token": my_getattr("access-token")}',
      'data': '{"teamTypeId":my_getattr("teamType"),"teamId":my_getattr("teamId"),"teamEmployeeId":my_getattr("employeeId"),"containApplyTo":my_randint(1,5)}',
      'files': '', 'sql': '', 'msg': '成功', 'result': 'PASS', 'proceed': '', 'tester': '',
      'testtime': '2020-02-16 00:20:35', 'sheet_name': 'home'},
     {'csv_loop': '', 'case_id': '0009_home_005', 'case_name': '获取首页信息',
      'url': 'https://mobile-test.qingzhuyun.com/api/mobile/home', 'method': 'GET',
      'header': '{"content-type": "application/json","access-token": my_getattr("access-token")}', 'data': '',
      'files': '', 'sql': '', 'msg': '成功', 'result': 'PASS',
      'proceed': 'my_setattr("teamId",response["data"]["teamId"])', 'tester': '', 'testtime': '2020-02-16 00:20:36',
      'sheet_name': 'home'}, {'csv_loop': 'login.xlsx/home', 'case_id': '0010_home_006', 'case_name': '循环测试1',
                              'url': 'https://mobile-test.qingzhuyun.com/api/mobile/base/userInfo/getEmployeeStates',
                              'method': 'GET',
                              'header': '{"content-type": "application/json","access-token": my_getattr("access-token")}',
                              'data': '', 'files': '', 'sql': '', 'msg': '成功', 'result': '', 'proceed': '',
                              'tester': '', 'testtime': '', 'sheet_name': 'home'},
     {'csv_loop': 'login.xlsx/home', 'case_id': '0011_home_006', 'case_name': '循环测试2',
      'url': 'https://mobile-test.qingzhuyun.com/api/mobile/base/userInfo/getEmployeeStates', 'method': 'GET',
      'header': '{"content-type": "application/json","access-token": my_getattr("access-token")}', 'data': '',
      'files': '', 'sql': '', 'msg': '成功', 'result': '', 'proceed': '', 'tester': '', 'testtime': '',
      'sheet_name': 'home'}, {'csv_loop': 'login.xlsx/home', 'case_id': '0012_home_006', 'case_name': '循环测试3',
                              'url': 'https://mobile-test.qingzhuyun.com/api/mobile/base/userInfo/getEmployeeStates',
                              'method': 'GET',
                              'header': '{"content-type": "application/json","access-token": my_getattr("access-token")}',
                              'data': '', 'files': '', 'sql': '', 'msg': '成功', 'result': '', 'proceed': '',
                              'tester': '', 'testtime': '', 'sheet_name': 'home'},
     {'csv_loop': 'login.xlsx/home', 'case_id': '0013_home_006', 'case_name': '循环测试4',
      'url': 'https://mobile-test.qingzhuyun.com/api/mobile/base/userInfo/getEmployeeStates', 'method': 'GET',
      'header': '{"content-type": "application/json","access-token": my_getattr("access-token")}', 'data': '',
      'files': '', 'sql': '', 'msg': '成功', 'result': '', 'proceed': '', 'tester': '', 'testtime': '',
      'sheet_name': 'home'}, {'csv_loop': 'login.xlsx/home', 'case_id': '0014_home_006', 'case_name': '循环测试5',
                              'url': 'https://mobile-test.qingzhuyun.com/api/mobile/base/userInfo/getEmployeeStates',
                              'method': 'GET',
                              'header': '{"content-type": "application/json","access-token": my_getattr("access-token")}',
                              'data': '', 'files': '', 'sql': '', 'msg': '成功', 'result': '', 'proceed': '',
                              'tester': '', 'testtime': '', 'sheet_name': 'home'},
     {'csv_loop': 'login.xlsx/home', 'case_id': '0015_home_006', 'case_name': '循环测试6',
      'url': 'https://mobile-test.qingzhuyun.com/api/mobile/base/userInfo/getEmployeeStates', 'method': 'GET',
      'header': '{"content-type": "application/json","access-token": my_getattr("access-token")}', 'data': '',
      'files': '', 'sql': '', 'msg': '成功', 'result': '', 'proceed': '', 'tester': '', 'testtime': '',
      'sheet_name': 'home'}, {'csv_loop': 'login.xlsx/home', 'case_id': '0016_home_006', 'case_name': '循环测试7',
                              'url': 'https://mobile-test.qingzhuyun.com/api/mobile/base/userInfo/getEmployeeStates',
                              'method': 'GET',
                              'header': '{"content-type": "application/json","access-token": my_getattr("access-token")}',
                              'data': '', 'files': '', 'sql': '', 'msg': '成功', 'result': '', 'proceed': '',
                              'tester': '', 'testtime': '', 'sheet_name': 'home'},
     {'csv_loop': 'login.xlsx/home', 'case_id': '0017_home_006', 'case_name': '循环测试8',
      'url': 'https://mobile-test.qingzhuyun.com/api/mobile/base/userInfo/getEmployeeStates', 'method': 'GET',
      'header': '{"content-type": "application/json","access-token": my_getattr("access-token")}', 'data': '',
      'files': '', 'sql': '', 'msg': '成功', 'result': '', 'proceed': '', 'tester': '', 'testtime': '',
      'sheet_name': 'home'}, {'csv_loop': 'login.xlsx/login', 'case_id': '0018_login', 'case_name': '正常登录',
                              'url': 'https://mobile-test.qingzhuyun.com/api/mobile/login', 'method': 'post',
                              'header': '{"content-type": "application/json"}',
                              'data': {'userName': '13290021660', 'password': 'e10adc3949ba59abbe56e057f20f883e'},
                              'files': '', 'sql': '', 'msg': '', 'result': 'PASS',
                              'proceed': '[my_setattr("access-token",response["data"]["access-token"]),my_setattr("userId",response["data"]["userId"])]',
                              'tester': '', 'sheet_name': 'login'},
     {'csv_loop': 'login.xlsx/login', 'case_id': '0019_login', 'case_name': '错误用户名登录',
      'url': 'https://mobile-test.qingzhuyun.com/api/mobile/login', 'method': 'post',
      'header': '{"content-type": "application/json"}',
      'data': {'userName': '1329002166', 'password': 'e10adc3949ba59abbe56e057f20f883e'}, 'files': '', 'sql': '',
      'msg': '用户名或密码错误', 'result': 'PASS', 'proceed': '', 'tester': '', 'sheet_name': 'login'},
     {'csv_loop': 'login.xlsx/login', 'case_id': '0020_login', 'case_name': '错误密码登录',
      'url': 'https://mobile-test.qingzhuyun.com/api/mobile/login', 'method': 'post',
      'header': '{"content-type": "application/json"}', 'data': {'userName': '13290021660', 'password': '123546'},
      'files': '', 'sql': '', 'msg': '用户名或密码错误', 'result': 'PASS', 'proceed': '', 'tester': '', 'sheet_name': 'login'},
     {'csv_loop': 'login.xlsx/login', 'case_id': '0021_login', 'case_name': '空用户名登录',
      'url': 'https://mobile-test.qingzhuyun.com/api/mobile/login', 'method': 'post',
      'header': '{"content-type": "application/json"}',
      'data': {'userName': '', 'password': 'e10adc3949ba59abbe56e057f20f883e'}, 'files': '', 'sql': '', 'msg': '无效的参数',
      'result': 'PASS', 'proceed': '', 'tester': '', 'sheet_name': 'login'},
     {'csv_loop': 'login.xlsx/login', 'case_id': '0022_login', 'case_name': '空密码登录',
      'url': 'https://mobile-test.qingzhuyun.com/api/mobile/login', 'method': 'post',
      'header': '{"content-type": "application/json"}', 'data': {'userName': '13290021660', 'password': ''},
      'files': '', 'sql': '', 'msg': '无效的参数', 'result': 'PASS', 'proceed': '', 'tester': '', 'sheet_name': 'login'}]
